// <auto-generated />
using System;
using HotelDb.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelDb.DataLayer.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20191113124404_initializeCreate")]
    partial class initializeCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0-preview2.19525.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelDb.DataLayer.Entities.BookingDL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DayFrom")
                        .HasColumnType("date");

                    b.Property<DateTime>("DayTill")
                        .HasColumnType("date");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("WithKids")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelDb.DataLayer.Entities.ClientDL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("BookingDLId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClientInfo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BookingDLId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("HotelDb.DataLayer.Entities.HolidayListDL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HolidayDay")
                        .HasColumnType("date");

                    b.Property<string>("HolidayName")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("HolidayList");
                });

            modelBuilder.Entity("HotelDb.DataLayer.Entities.InvoiceDL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(6,0)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("HotelDb.DataLayer.Entities.RoomDL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingDLId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NumberBeds")
                        .HasColumnType("int");

                    b.Property<bool>("Ready")
                        .HasColumnType("bit");

                    b.Property<string>("RoomInfo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("RoomPriceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingDLId");

                    b.HasIndex("RoomPriceId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelDb.DataLayer.Entities.RoomPriceDL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal>("HolidayPrice")
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal>("WeekendPrice")
                        .HasColumnType("decimal(5,0)");

                    b.HasKey("Id");

                    b.ToTable("RoomPrice");
                });

            modelBuilder.Entity("HotelDb.DataLayer.Entities.BookingDL", b =>
                {
                    b.HasOne("HotelDb.DataLayer.Entities.ClientDL", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("HotelDb.DataLayer.Entities.InvoiceDL", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("HotelDb.DataLayer.Entities.ClientDL", b =>
                {
                    b.HasOne("HotelDb.DataLayer.Entities.BookingDL", null)
                        .WithMany("GuestList")
                        .HasForeignKey("BookingDLId");
                });

            modelBuilder.Entity("HotelDb.DataLayer.Entities.RoomDL", b =>
                {
                    b.HasOne("HotelDb.DataLayer.Entities.BookingDL", null)
                        .WithMany("RoomList")
                        .HasForeignKey("BookingDLId");

                    b.HasOne("HotelDb.DataLayer.Entities.RoomPriceDL", "RoomPrice")
                        .WithMany()
                        .HasForeignKey("RoomPriceId");
                });
#pragma warning restore 612, 618
        }
    }
}
